


class Inscricao < ApplicationRecord

    # extends ...................................................................
    # includes ..................................................................
    audited
    acts_as_paranoid

    include Searchrable

    # security (i.e. attr_accessible) ...........................................
    enum sexo: { masculino: "masculino", feminino: "feminino" }

    # relationships .............................................................
    has_one :Curso, class_name: "Curso", foreign_key: "Curso_id"
    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
end
